### ISSUE TITLE
Example has two python's

### ISSUE THREAD

**Issue by flip111** [tweag/jupyterWith#101]
When i run the example https://github.com/tweag/jupyterWith#getting-started a JupyterLab webpage opens up with under notebook and console (introduction page) two times python and one time haskell:

* Python 3
* Haskell - haskell
* Python 3 - python

Why is there two times python? Which one should i choose for which purpose?

On a side note i think the Haskell button can do without mentioning haskell two times. Maybe "Haskell - GHC 8.8.3" would be a bit more useful.

**Comment by flip111** [comment]
The first "Python 3" button doesn't work as well as the second one. That is a tried adding a python package and python could not find it.

**Comment by guaraqe** [comment]
Jupyter always comes loaded with a Python kernel by default, and it is just bare-bones. Any Python kernel one adds via JupyterWith will appear as a second one.

The `haskell` and `python` that you see besides the language name are the parameter `name` given to `iPythonWith` and `iHaskellWith`. So they are configurable., if y ou change them in the Nix file, they will change in the Jupyter interface.

**Comment by flip111** [comment]
Maybe it's possible to patch/modify the default jupyter installation. The default python kernel seems useless in this scenario.

https://github.com/jupyter/notebook/issues/3674
https://stackoverflow.com/questions/42635310/remove-kernel-on-jupyter-notebook
https://stackoverflow.com/questions/31976367/how-do-i-delete-refresh-available-kernels-for-ipython-jupyter-notebook-v4-0

**Comment by guaraqe** [comment]
I tried following the links, I think this is not possible for JupyterWith now. The reason for this is that for:

- whitelisting only JupyterWith kernels, or
- removing the default kernel

one needs to change configurations in the `jupyter_notebook_config.py` file. For this to have any value for JupyterWith, this should be declarative and static, i.e. in the Nix store. But Jupyter needs for this file to be writable (I don't know why):

```
OSError: [Errno 30] Read-only file system: '/nix/store/96cvm1x38jk4cj51v46n6cw5xg36bi54-jupyter-config-dir/migrated'
```

so that doesn't work. There are many issues with Jupyter asking for everything to be mutable, this happens often.

I don't see a reasonable solution for this now, so I will close this issue. Maybe there will be a simpler way in the future.
