### ISSUE TITLE
"jupyterlab-ihaskell" is not a valid npm package

### ISSUE THREAD

**Issue by jamesdbrock** [tweag/jupyterWith#111]
**Describe the bug**

Most builds in the `example/Haskell` directories fail with

`ValueError: "jupyterlab-ihaskell" is not a valid npm package`

**To Reproduce**

```bash
cd example/Haskell/diagrams
nix-shell
```

**Environment**
 - OS name + version: Fedora 32 (Workstation Edition)
 - Version of the code: 
   - `commit cf250916cd633db85342531b9d90e655d0e650ab`
      `Date:   Mon Jul 20 10:41:51 2020 +0500`

**Additional context**

`example/Haskell/local-package` works. Maybe because it has a `package.json`?

**Comment by jamesdbrock** [comment]
Actually it's possible that is problem is related to when I bumped the __ihaskell_labextension__ version to 0.0.7 for JupyterLab 2 in April?

https://github.com/gibiansky/IHaskell/issues/1159

I don't understand where version 0.0.9 of https://www.npmjs.com/package/jupyterlab-ihaskell comes from.

**Comment by guaraqe** [comment]
This is because these examples are using the impure interface, which needs extra precautions, as described here: https://github.com/tweag/jupyterWith#impure-generator


However, last time I checked, the IHaskell lab extension was not yet working with Jupyter 2, and it will not find a compatible version. @MMesch Do you have any news concerning this?

**Comment by jamesdbrock** [comment]
> This is because these examples are using the impure interface

Oh yeah, when I `nix-shell --option sandbox false` then I get the error

```
ValueError: No version of jupyterlab-ihaskell could be found that is compatible with the current version of JupyterLab.

Conflicting Dependencies:
JupyterLab              Extension      Package
>=2.1.0 <2.2.0          >=1.0.0 <2.0.0 @jupyterlab/application
...
```

So, let's talk about that.

The source code for __ihaskell-labextension__ is in [`IHaskell/ihaskell_labextension`](https://github.com/gibiansky/IHaskell/tree/master/ihaskell_labextension).

I upgraded __ihaskell-labextension__ to JupyterLab 2 and assigned that to be version __0.0.7__ in https://github.com/gibiansky/IHaskell/pull/1151 . For my own projects I build __ihaskell-labextension__ right out of the source directory so that works fine for me.

When I upgraded __ihaskell-labextension__ from version __0.0.6__ to __0.0.7__ for JupyterLab 2, I didn't know about the NPM package https://www.npmjs.com/package/jupyterlab-ihaskell , which is already on version __0.0.9__, which suggests to me that maybe there is another *IHaskell* repo fork somewhere in which __haskell-labextension__ is on 0.0.9?

*jupyterWith* generally assumes that extensions come from NPM.
https://github.com/tweag/jupyterWith/blob/41ef8935b2a0eb1ee8729fd53cf4b08313541628/lib/directory.nix#L133

Or maybe *jupyterWith* could build the extension from the *IHaskell* repo? You wrote `mkDirectoryFromLockFile` @guaraqe , could this be used instead of `mkDirectoryWith` to build __ihaskell-labextension__ from the *IHaskell* repo instead of NPM?
https://github.com/tweag/jupyterWith/blob/41ef8935b2a0eb1ee8729fd53cf4b08313541628/lib/directory.nix#L53

Also, @guaraqe , could you contatct @MMesch to ask him what his plans are for the NPM package https://www.npmjs.com/package/jupyterlab-ihaskell ? I think you should have admin permission on that package too. Probably also @vaibhavsagar .

**Comment by jamesdbrock** [comment]
> Also, guaraqe , could you contatct MMesch

Oh, never mind, I thought MMesch was a member of Tweag, I guess he's not.

**Comment by jamesdbrock** [comment]
(I DMed MMesch on Twitter)

**Comment by vaibhavsagar** [comment]
I do have access! What would you like me to do with it?

**Comment by jamesdbrock** [comment]
> I do have access! What would you like me to do with it?

Hi Vaibhav! Maybe, figure out where the “version __0.0.9__” of https://www.npmjs.com/package/jupyterlab-ihaskell comes from? 'Cause it's not coming from here:

https://github.com/gibiansky/IHaskell/blob/49b03cf5a9a8e8f38a617551b80acf081f4ecc14/ihaskell_labextension/package.json#L3

And then, maybe bump the version to __0.1.0__ and publish the Jupyterlab-2-compatible https://www.npmjs.com/package/jupyterlab-ihaskell ?

**Comment by MMesch** [comment]
Hey all,

I am on vacation atm. Just quickly sone info: I bumped the npm version
twice _without_ updating it on the ihaskell repo to make it compatible with
new jupyterlab releases. It wasn't clean to do this without updating the
ihaskell repo. But there are no other changes to the extension than larger
jupyterlab version bounds.

I didn't manage to give generous version bounds with npm while jupyterlab
was on version 0.x.x due to how node works. But now it might be easier. We
should now probably give very generous version bounds because the extension
is not tightly coupled to jupyterlab and all of this bumping is a lot of
work.

I and vaibhav have access to the npm package. Happy to include more people.
It'll just gave to wait until September when I am back.

I hope this helps a bit.


James Brock <notifications@github.com> schrieb am Di., 18. Aug. 2020, 09:09:

**Comment by jamesdbrock** [comment]
Okay thank you @MMesch .
